[package]
name = "share-clip"
version = "0.3.2"
authors = ["morning"]
edition = "2018"
description = "Multi-device clipboard sharing."
homepage = "https://github.com/cc-morning/share-clip"
repository = "https://github.com/cc-morning/share-clip"

[dependencies]
anyhow = { version = "1", default-features = false, features = [ "std" ] }
arboard = { version = "2", default-features = false, features = [ "image-data" ] }
base64 = { version = "0.13", default-features = false, features = [ "std" ] }
bincode = { version = "1", default-features = false }
clap = { version = "2", default-features = false }
clipboard-master = { git = "https://github.com/cc-morning/clipboard-master.git" }
crypto_box = { version = "0.7", default-features = false, features = [ "alloc", "u64_backend" ] }
deadpool-redis = { version = "0.9", default-features = false, features = [ "rt_tokio_1" ] }
futures-util = { version = "0.3", default-features = false }
notify-rust = { version = "4", default-features = false, features = [ "z" ] }
md5 = { version = "0.7", default-features = false }
mimalloc = { version = "0.1", default-features = false }
rand = { version = "0.8", default-features = false, features = [ "std" ] }
redis = { version = "0.21", default-features = false, features = [ "tokio-comp" ] }
serde = { version = "1", default-features = false, features = [ "derive" ] }
tokio = { version = "1", default-features = false, features = [ "macros", "rt-multi-thread", "sync", "time" ] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
