[package]
name = "share-clip"
version = "0.1.0"
authors = ["morning"]
edition = "2018"
description = "Multi-device clipboard sharing."
homepage = "https://github.com/cc-morning/share-clip"
repository = "https://github.com/cc-morning/share-clip"

[dependencies]
anyhow = { version = "1", default-features = false, features = [ "std" ] }
base64 = { version = "0.13", default-features = false, features = [ "std" ] }
bincode = { version = "1", default-features = false }
clap = { version = "2", default-features = false }
# clipboard = { path = "/home/morning/Projects/rust-clipboard" }
clipboard = { version = "0.5" }
ctrlc = { version = "3", default-features = false }
deadpool-redis = { version = "0.9", default-features = false, features = [ "rt_tokio_1" ] }
futures-util = { version = "0.3", default-features = false }
lazy_static = { version = "1", default-features = false }
mimalloc = { version = "0.1", default-features = false }
rand = { version = "0.8", default-features = false }
rayon = { version = "1", default-features = false }
redis = { version = "0.21", default-features = false, features = [ "tokio-comp" ] }
rsa = { version = "0.5", default-features = true, features = [ "std", "serde" ] }
tokio = { version = "1", default-features = false, features = [ "macros", "rt-multi-thread", "sync", "time" ] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

